Link pg_backup_ctl++ explicitely against libpthread.
CentOS 8 complains about

       undefined reference to symbol 'pthread_rwlock_unlock@@GLIBC_2.2.5'

which indicates that libpthread support isn't properly added during link time.

I'm far too lazy to debug why this works on Fedora, CentOS 6/7 and Debian,
and since we need to explicitely link librt on SLES add it without
further digging.